app/views/chapter/show.blade.php
Adding the current time in grade to the list of crew for a given chapter.
=> Chapter display changes

app/models/Chapter.php, app/views/partials/subchaptercrew.blade.php, javascript/main.js, public/js/bundle.js
Partial page, javascript updates, and necessary updates to the chapter model to support the same.
=> Subchapterroster

app/controllers/BilletController.php, app/models/Billet.php, app/routes.php, app/views/billet/create.blade.php, app/views/billet/index.blade.php, app/views/billets/create.blade.php, app/views/nav.blade.php, javascript/main.js, public/js/bundle.js
New billet management functions, should resolve issue #64
=> Billet management

app/controllers/ChapterController.php
=> Added Branch and Billet fields to chapter report export. 

app/Awards/AwardQualification.php
There is only ESWP and OSWP. Don't blindly use the first character of their paygrade
=> Bolthole Tickets 2238 & 2239

app/User.php
Don't do intval() on the config array for that type of promotion points!
=> Bolthole Ticket 2240

app/Awards/AwardQualification.php, app/Http/Controllers/UserController.php, app/User.php, config/awards.php
Make number of days to delay display of awards configurable
=> Make date comparison logic clearer

app/User.php
(https://bolthole.trmn.org/scp/tickets.php?id=2411)
=> Fixed bug with promoting SFC members 

app/User.php
=> Fixed infinite loop in adult SFC promotion check

app/User.php
=> Merge develop into master

app/Http/Controllers/UserController.php, app/User.php
* Updated how the Request object was used
* Cleaned up doc blocks
* Cleaned up code formatting
=> * Fixed issue with phone number validator

app/Http/Controllers/UserController.php, app/User.php
* Improved performance of getNextMemberId()
* Deprecated getFirstAvailableMemberId()
* Doc block clean up
=> Hotfix -- 500 errors when approving applications

.shift
This pull request includes minor version updates for your package dependencies as well as major version updates for packages with known compatibility. Feel free to commit any additional changes to the `shift-du-20190625` branch.
**Before merging**, you should:
- Checkout the `shift-du-20190625` branch
- Review **all** pull request comments for additional changes
- Run `composer update`
- Thoroughly test your application
=> Dependency Updater

app/User.php, database/migrations/2025_03_24_162130_tt005162_add_ian_peerage_titles.php
- Add IAN peerage titles according to https://wiki.trmn.org/wiki/index.php/Lords:Forms_of_address#Gendered_Titles_and_the_Peerage
=> Bolthole 005162: Add new IAN peerage titles

app/Common/UpdatePaygrades.php, app/Common/UpdateRatings.php, database/migrations/2025_02_16_121816_tt005211_update_rhn_paygrades.php, database/migrations/2025_02_16_121820_tt005211_update_diplomatic_ratings.php, database/migrations/2025_02_16_121823_tt005211_update_intel_ratings.php, database/migrations/2025_02_16_121825_tt005211_update_rmacs_paygrades.php, database/migrations/2025_02_16_121828_tt005211_update_rmmm_basic_ratings.php, database/migrations/2025_02_16_121829_tt005211_update_rmmm_deck_ratings.php, database/migrations/2025_02_16_121831_tt005211_update_rmmm_eng_ratings.php, database/migrations/2025_02_16_121834_tt005211_update_rmmm_catering_ratings.php, database/migrations/2025_02_16_121836_tt005211_update_rmmm_medical_ratings.php, database/migrations/2025_02_16_121839_tt005211_update_sfc_paygrades.php, database/migrations/2025_02_16_124413_tt05211_insert_sfc_probational_paygrades.php
Update ranks/titles according to a spreadsheet of changes provided by BuPers.
Rollback requires a restore from backup, given the structure of the data and how widespread the changes are.
=> Bolthole 005211 - Update ranks/titles

database/migrations/2025_04_24_125427_tt005543_fixup_sxc_post_nominal.php
Add SXC post-nominal to Sphinx Cross
=> TT005543 - Add SXC post-nominal to Sphinx Cross.

resources/views/nav.blade.php
Remove the refererences/links to MEDUSA mobile.
=> TT005543 - Remove references to MEDUSA mobile

resources/views/nav.blade.php
- Fix navbar to include entries to show RMN, RMACS and CIVIL (Intel) members.
=> TT 004220 - Permission set issues

resources/views/report/chapter-create.blade.php, resources/views/report/chapter-edit.blade.php, resources/views/report/chapter-email.blade.php, resources/views/report/chapter-show.blade.php
- Remove the date of birth from the bimonthly reports, since this is PII.
=> TT005554  -  remove dob from reports

app/Console/Commands/purgeDeniedUsers.php
- Add an artisan command to purge denied users which applied more than 30 days ago.
=> TT003879 - Purge denied users

app/Promotions/MedusaPromotions.php
- Several return points from getPromotableInfo() return an array with the next index missing. Add in that index with a value of an empty array.
=> Fix return values from getPromotableInfo()

app/Http/Controllers/PromotionController.php, app/Promotions/MedusaPromotions.php, database/migrations/2025_06_06_111817_update_promotion_requirements.php
- Fix it so that flag and provisional promotions show up in the promotion report.
No database rollback required for deployment to medusa-dev.
=> Fix promotions

app/Http/Controllers/UserController.php, resources/views/user/index.blade.php, routes/web.php
TT005596 - Add export to List Members to export to CSV.
=> TT005596 - Add exporter from List Members to export to CSV.

app/Http/Controllers/UserController.php
- Add a guardrail check for an empty assignment to the code for logging the removal of billets.
=> TT005599 - Add in check for empty assignment

app/Http/Controllers/UserController.php, resources/views/user/index.blade.php
- Add logic to filter to export users celebrating their 5*n year anniversary during the current month.
=> TT005596 - Add logic to filter to anniversary month/year users only.

app/Http/Controllers/ExamController.php, resources/views/exams/list.blade.php, routes/web.php
- Add web route
- Add controller method
- Update view
NOTE: The calculation of points should probably go onto the ExamList model.
=> Add examExport to the exam list page and exam controller.
